services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - 8000:8000
    restart: always
    volumes:
      - './data:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal

  dynamodb-admin: 
    image: "aaronshaf/dynamodb-admin"
    container_name: dynamodb-admin
    depends_on:
      - dynamodb-local
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=local

  backend:
    image: node:20-alpine
    working_dir: /home/node
    command: sh -c "yarn install && yarn start"
    depends_on:
      - dynamodb-local
    restart: unless-stopped
    ports:
      - 3010:3010
    volumes:
      - "./backend:/home/node"

  backend_worker:
    image: node:20-alpine
    working_dir: /home/node
    command: sh -c "yarn start:worker"
    depends_on:
      - mysql_backend
      - backend
    restart: unless-stopped
    environment:
      - DATABASE_HOST=mysql_backend
      - DATABASE_NAME=backend
      - DATABASE_USER=backend
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=3306
    links:
      - mysql_backend
    volumes:
      - "./backend:/home/node"

  frontend:
    image: node:20-alpine
    working_dir: /home/node
    command: sh -c "yarn install && yarn start"
    restart: unless-stopped
    volumes:
      - "./frontend:/home/node"
    ports:
      - 3000:3000
