services:
  mysql_backend:
      image: mysql
      environment:
        - MYSQL_DATABASE=backend
        - MYSQL_USER=backend
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_PORT=3306
      ports:
        - 3306:3306
      volumes:
        - 'mysql_backend_data:/data/db'

  backend:
    image: node:18-alpine
    working_dir: /home/node
    command: sh -c "yarn install && yarn start"
    depends_on:
      - mysql_backend
    restart: unless-stopped
    ports:
      - 3010:3010
    environment:
      - DATABASE_HOST=mysql_backend
      - DATABASE_NAME=backend
      - DATABASE_USER=backend
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=3306
    links:
      - mysql_backend
    volumes:
      - "./backend:/home/node"

  backend_worker:
    image: node:18-alpine
    working_dir: /home/node
    command: sh -c "yarn start:worker"
    depends_on:
      - mysql_backend
      - backend
    restart: unless-stopped
    environment:
      - DATABASE_HOST=mysql_backend
      - DATABASE_NAME=backend
      - DATABASE_USER=backend
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=3306
    links:
      - mysql_backend
    volumes:
      - "./backend:/home/node"

  frontend:
    image: node:18-alpine
    working_dir: /home/node
    command: sh -c "yarn start"
    restart: unless-stopped
    volumes:
      - "./frontend:/home/node"
    ports:
      - 3000:3000

volumes:
  mysql_backend_data:
